### ISSUE TITLE
ReferenceError: postman is not defined

### ISSUE THREAD

**Issue by Ray-Barker** [Ne4istb/postman-combine-collections#4]
After installing I get this:
`> postman-combine-collections -V
Thrown:
ReferenceError: postman is not defined`
Postman is installed, what did I miss?

**Comment by Ne4istb** [comment]
Hi @Ray-Barker ,

Please, try to run util without installing it:
```npx postman-combine-collections -V```

Will it work in this mode?

**Comment by Ray-Barker** [comment]
Hello @Ne4istb ,
Thanks for quick response, yes, it does work like that, shows the version 1.1.0

**Comment by Ne4istb** [comment]
Ok,
It looks something is wrong inside your repository. You can try next:
- reinstall npm dependency ```npm install postman-combine-collections --save```
- install it globally ```npm install postman-combine-collections -g```
- continue to use it without explicit installation with ```npx postman-combine-collections [options```]

**Comment by Ray-Barker** [comment]
Thanks a lot, installation won't work for me, but using `npx postman-combine-collections` works perfectly. Your tool saved me whole day of work, cheers!
