### ISSUE TITLE
Only one collection is added

### ISSUE THREAD

**Issue by teampurpledev** [Ne4istb/postman-combine-collections#5]
In the /collections folder I have 10 collections. 

```
nodejs index.js -f ../collections/* -o test
```
**Output**:

```
Collection 'Cart API' was successfully added.
Combined collection is saved to 'test'
```
Only one collection is added to that folder. Either the recursive function does not work as expected or I'm using this tool wrong - just hoping to get some clarification. Ty!

**Comment by Ne4istb** [comment]
Hi @sweetnoods
Please, take a look at #1

Looks like I have to add this info to the readme file:)

**Comment by teampurpledev** [comment]
Ah I see. I should have wrapped my argument in quotes, but yes, that would be helpful to add in the README
```
nodejs index.js -f '../collections/*' -o test`
```
