### ISSUE TITLE
Collection combine not working 

### ISSUE THREAD

**Issue by ahghatol** [Ne4istb/postman-combine-collections#7]
I was trying to merge two collections using this module but it merging only one. 
Check the below example, it saying only **Collection 'Program_API's' was successfully added**, it's not adding another **Contributor** collection 

> postman-combine-collections --name composed  -f Contributor.postman_collection.json  -f Program_APIs.postman_collection.json  -o composed.collection.json 

> Collection 'Program_API's' was successfully added.
> Combined collection is saved to 'composed.collection.json'

**Comment by Ne4istb** [comment]
hi @ahghatol 

You are specifying path flag (-f) several times. 
-f applies a path to a specific file or shell wildcard (globs). 

So, in your case, it should be either all collection files:
```bash
postman-combine-collections --name composed -f *.postman_collection.json  -o composed.collection.json
```
or specific files
```bash
postman-combine-collections --name composed -f {Contributor,Program_APIs}.postman_collection.json  -o composed.collection.json
```

Please, check [glob-npm](https://www.npmjs.com/package/glob) and [How To Use Bash Wildcards For Globbing](https://www.shell-tips.com/bash/wildcards-globbing/) to understand globbing better.
